In [185]:
import pandas as pd

NRI subset

In [186]:
NRI_data = pd.read_csv('/Users/alejandroroacontreras/Library/CloudStorage/GoogleDrive-alejandro.roa.cs@gmail.com/Mi unidad/Pardee Rand Graduate School/Year 2/Introduction to ML/code/PRGS-Intro-to-ML-2024/data/raw/NRI_counties_level.csv', dtype={'STCOFIPS':str})

In [187]:
NRI_data.shape

(3231, 465)

In [188]:
STCOFIPS_column = 'STCOFIPS'

In [189]:
columns_selection = [STCOFIPS_column] + [col for col in NRI_data.columns if col.endswith('_AFREQ') or col.endswith('_RISKR')]

In [190]:
subset_NRI = NRI_data[columns_selection]

In [191]:
subset_NRI.head()

,STCOFIPS,AVLN_AFREQ,AVLN_RISKR,CFLD_AFREQ,CFLD_RISKR,CWAV_AFREQ,CWAV_RISKR,DRGT_AFREQ,DRGT_RISKR,ERQK_AFREQ,...,TRND_AFREQ,TRND_RISKR,TSUN_AFREQ,TSUN_RISKR,VLCN_AFREQ,VLCN_RISKR,WFIR_AFREQ,WFIR_RISKR,WNTW_AFREQ,WNTW_RISKR
0,01001,NaN,Not Applicable,NaN,Not Applicable,0.0,No Rating,25.969774,Relatively Low,0.000431,...,0.480184,Relatively Moderate,NaN,Not Applicable,NaN,Not Applicable,0.000035,Very Low,0.433437,Very Low
1,01003,NaN,Not Applicable,3.684142,Relatively Low,0.0,No Rating,12.353442,Relatively Moderate,0.000338,...,0.953140,Relatively Moderate,NaN,Insufficient Data,NaN,Not Applicable,0.002229,Relatively Moderate,0.182759,Relatively Low
2,01005,NaN,Not Applicable,NaN,Not Applicable,0.0,No Rating,43.956953,Relatively Low,0.000227,...,0.739018,Relatively Moderate,NaN,Not Applicable,NaN,Not Applicable,0.000038,Very Low,0.185759,Very Low
3,01007,NaN,Not Applicable,NaN,Not Applicable,0.0,No Rating,28.894501,Very Low,0.000790,...,0.586160,Relatively Moderate,NaN,Not Applicable,NaN,Not Applicable,0.000040,Very Low,0.743034,Very Low
4,01009,NaN,Not Applicable,NaN,Not Applicable,0.0,No Rating,28.152598,Relatively Low,0.000817,...,0.710332,Relatively Moderate,NaN,Not Applicable,NaN,Not Applicable,0.000035,Very Low,0.866873,Very Low

SVI subset

In [192]:
SVI_data = pd.read_csv('/Users/alejandroroacontreras/Library/CloudStorage/GoogleDrive-alejandro.roa.cs@gmail.com/Mi unidad/Pardee Rand Graduate School/Year 2/Introduction to ML/code/PRGS-Intro-to-ML-2024/data/raw/SVI_counties_level.csv', dtype={'FIPS':str})

In [193]:
SVI_columns_selection = ['ST', 'STATE', 'ST_ABBR', 'STCNTY', 'COUNTY', 'FIPS', 'LOCATION', 'AREA_SQMI', 'E_TOTPOP', 
                      'EP_POV150', 'EP_UNEMP', 'EP_HBURD', 'EP_NOHSDP', 'EP_UNINSUR', 'EP_AGE65', 'EP_AGE17', 
                      'EP_DISABL', 'EP_SNGPNT', 'EP_LIMENG', 'EP_MINRTY', 'EP_MUNIT', 'EP_MOBILE', 'EP_CROWD', 
                      'EP_NOVEH', 'EP_GROUPQ', 'EP_NOINT', 'EP_AFAM', 'EP_HISP', 'EP_ASIAN', 'EP_AIAN', 'EP_NHPI', 
                      'EP_TWOMORE', 'EP_OTHERRACE']

In [194]:
subset_SVI = SVI_data[SVI_columns_selection]

In [195]:
subset_SVI.head(1000)

,ST,STATE,ST_ABBR,STCNTY,COUNTY,FIPS,LOCATION,AREA_SQMI,E_TOTPOP,EP_POV150,...,EP_NOVEH,EP_GROUPQ,EP_NOINT,EP_AFAM,EP_HISP,EP_ASIAN,EP_AIAN,EP_NHPI,EP_TWOMORE,EP_OTHERRACE
0,1,Alabama,AL,1001,Autauga County,01001,"Autauga County, Alabama",594.454786,58761,20.2,...,4.0,0.9,10.9,19.6,3.2,1.1,0.1,0.0,3.3,0.2
1,1,Alabama,AL,1003,Baldwin County,01003,"Baldwin County, Alabama",1589.861817,233420,18.3,...,2.3,1.5,10.9,8.3,4.8,0.9,0.2,0.0,3.1,0.4
2,1,Alabama,AL,1005,Barbour County,01005,"Barbour County, Alabama",885.007619,24877,37.7,...,11.7,12.0,31.8,46.9,4.8,0.5,0.3,0.0,1.8,1.2
3,1,Alabama,AL,1007,Bibb County,01007,"Bibb County, Alabama",622.469286,22251,29.0,...,7.5,6.4,20.2,20.7,2.9,0.3,0.1,0.0,1.7,0.1
4,1,Alabama,AL,1009,Blount County,01009,"Blount County, Alabama",644.890376,59077,22.9,...,4.8,1.0,16.9,1.2,9.7,0.2,0.1,0.2,2.8,0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,21,Kentucky,KY,21001,Adair County,21001,"Adair County, Kentucky",405.292252,18887,32.1,...,5.5,6.6,18.1,1.6,2.5,0.3,0.0,0.1,3.8,0.0
996,21,Kentucky,KY,21003,Allen County,21003,"Allen County, Kentucky",343.723827,20773,26.6,...,6.4,0.9,20.3,0.8,2.4,0.0,0.0,0.0,2.3,0.3
997,21,Kentucky,KY,21005,Anderson County,21005,"Anderson County, Kentucky",202.259456,23839,20.9,...,1.9,0.4,12.7,3.1,2.2,0.1,0.0,0.1,1.9,0.0
998,21,Kentucky,KY,21007,Ballard County,21007,"Ballard County, Kentucky",247.094722,7742,25.9,...,5.4,1.5,14.8,3.9,1.6,0.4,0.0,0.0,2.2,0.0
999,21,Kentucky,KY,21009,Barren County,21009,"Barren County, Kentucky",487.364968,44511,31.9,...,6.7,1.5,15.7,3.4,3.6,0.8,0.0,0.0,2.5,0.3

In [196]:
subset_SVI.rename(columns={'FIPS':'FIPS'})

,ST,STATE,ST_ABBR,STCNTY,COUNTY,FIPS,LOCATION,AREA_SQMI,E_TOTPOP,EP_POV150,...,EP_NOVEH,EP_GROUPQ,EP_NOINT,EP_AFAM,EP_HISP,EP_ASIAN,EP_AIAN,EP_NHPI,EP_TWOMORE,EP_OTHERRACE
0,1,Alabama,AL,1001,Autauga County,01001,"Autauga County, Alabama",594.454786,58761,20.2,...,4.0,0.9,10.9,19.6,3.2,1.1,0.1,0.0,3.3,0.2
1,1,Alabama,AL,1003,Baldwin County,01003,"Baldwin County, Alabama",1589.861817,233420,18.3,...,2.3,1.5,10.9,8.3,4.8,0.9,0.2,0.0,3.1,0.4
2,1,Alabama,AL,1005,Barbour County,01005,"Barbour County, Alabama",885.007619,24877,37.7,...,11.7,12.0,31.8,46.9,4.8,0.5,0.3,0.0,1.8,1.2
3,1,Alabama,AL,1007,Bibb County,01007,"Bibb County, Alabama",622.469286,22251,29.0,...,7.5,6.4,20.2,20.7,2.9,0.3,0.1,0.0,1.7,0.1
4,1,Alabama,AL,1009,Blount County,01009,"Blount County, Alabama",644.890376,59077,22.9,...,4.8,1.0,16.9,1.2,9.7,0.2,0.1,0.2,2.8,0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3139,56,Wyoming,WY,56037,Sweetwater County,56037,"Sweetwater County, Wyoming",10426.975770,42079,18.0,...,2.0,1.2,10.6,1.2,16.2,0.7,0.9,0.1,2.2,0.9
3140,56,Wyoming,WY,56039,Teton County,56039,"Teton County, Wyoming",3996.846933,23346,10.5,...,1.9,3.9,10.4,0.6,15.2,1.3,0.1,0.1,2.3,0.7
3141,56,Wyoming,WY,56041,Uinta County,56041,"Uinta County, Wyoming",2081.719807,20546,15.2,...,3.7,1.1,8.5,0.2,9.9,0.2,0.1,0.0,2.9,0.0
3142,56,Wyoming,WY,56043,Washakie County,56043,"Washakie County, Wyoming",2238.678265,7725,19.1,...,4.7,2.0,14.1,0.0,14.3,0.4,0.3,0.0,3.2,0.3
3143,56,Wyoming,WY,56045,Weston County,56045,"Weston County, Wyoming",2398.003893,6870,19.8,...,3.4,5.2,19.6,0.1,3.5,0.2,1.5,0.7,8.3,0.1

Merging both datasets

In [197]:
subset_NRI.rename(columns={'STCOFIPS': 'FIPS'}, inplace=True)

/var/folders/6x/dj5hjzzn65d2wm0xdv92rwyc0000gn/T/ipykernel_33328/4252012711.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_NRI.rename(columns={'STCOFIPS': 'FIPS'}, inplace=True)

In [198]:
merged_data = pd.merge(subset_NRI, subset_SVI, on='FIPS', how='outer')

In [199]:
merged_data.head(1000)

,FIPS,AVLN_AFREQ,AVLN_RISKR,CFLD_AFREQ,CFLD_RISKR,CWAV_AFREQ,CWAV_RISKR,DRGT_AFREQ,DRGT_RISKR,ERQK_AFREQ,...,EP_NOVEH,EP_GROUPQ,EP_NOINT,EP_AFAM,EP_HISP,EP_ASIAN,EP_AIAN,EP_NHPI,EP_TWOMORE,EP_OTHERRACE
0,01001,NaN,Not Applicable,NaN,Not Applicable,0.000000,No Rating,25.969774,Relatively Low,0.000431,...,4.0,0.9,10.9,19.6,3.2,1.1,0.1,0.0,3.3,0.2
1,01003,NaN,Not Applicable,3.684142,Relatively Low,0.000000,No Rating,12.353442,Relatively Moderate,0.000338,...,2.3,1.5,10.9,8.3,4.8,0.9,0.2,0.0,3.1,0.4
2,01005,NaN,Not Applicable,NaN,Not Applicable,0.000000,No Rating,43.956953,Relatively Low,0.000227,...,11.7,12.0,31.8,46.9,4.8,0.5,0.3,0.0,1.8,1.2
3,01007,NaN,Not Applicable,NaN,Not Applicable,0.000000,No Rating,28.894501,Very Low,0.000790,...,7.5,6.4,20.2,20.7,2.9,0.3,0.1,0.0,1.7,0.1
4,01009,NaN,Not Applicable,NaN,Not Applicable,0.000000,No Rating,28.152598,Relatively Low,0.000817,...,4.8,1.0,16.9,1.2,9.7,0.2,0.1,0.2,2.8,0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,20195,NaN,Not Applicable,NaN,Not Applicable,0.495356,Relatively Low,35.636364,Relatively Low,0.000149,...,2.8,2.5,14.4,0.1,0.8,0.4,0.1,0.0,2.0,0.0
996,20197,NaN,Not Applicable,NaN,Not Applicable,0.371517,Relatively Low,18.454545,Relatively Low,0.000219,...,2.3,1.7,18.3,1.0,4.9,0.7,0.2,0.1,2.7,0.0
997,20199,NaN,Not Applicable,NaN,Not Applicable,0.866873,Relatively Moderate,60.454545,Relatively Moderate,0.000118,...,4.1,1.5,11.8,0.7,6.8,0.6,0.3,0.0,2.5,0.0
998,20201,NaN,Not Applicable,NaN,Not Applicable,0.433437,Relatively Low,5.500386,Relatively Low,0.000150,...,3.0,2.4,26.8,0.2,4.4,0.7,0.3,0.0,1.6,0.5
999,20203,NaN,Not Applicable,NaN,Not Applicable,0.804954,Very High,56.636364,Relatively Moderate,0.000137,...,1.5,1.1,6.8,0.7,24.9,0.0,0.1,0.0,2.1,0.2

In [201]:
merged_data.to_csv('/Users/alejandroroacontreras/Library/CloudStorage/GoogleDrive-alejandro.roa.cs@gmail.com/Mi unidad/Pardee Rand Graduate School/Year 2/Introduction to ML/code/PRGS-Intro-to-ML-2024/data/processed/merged_data.csv', index=False)

In [202]:
df_check = pd.read_csv('/Users/alejandroroacontreras/Library/CloudStorage/GoogleDrive-alejandro.roa.cs@gmail.com/Mi unidad/Pardee Rand Graduate School/Year 2/Introduction to ML/code/PRGS-Intro-to-ML-2024/data/processed/merged_data.csv', dtype={'FIPS': str})

In [203]:
print(df_check['FIPS'].head())

0    01001
1    01003
2    01005
3    01007
4    01009
Name: FIPS, dtype: object